# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ fetchurl }:

self: super: {
  "google-cloud-aiplatform" = super.buildPythonPackage {
    pname = "google-cloud-aiplatform";
    version = "1.88.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/59/6a0921180a825e0bf034b39a591446ca17ff5fafa194b96cd0e502d0ca99/google_cloud_aiplatform-1.88.0-py2.py3-none-any.whl";
      sha256 = "1wgncfzxnk55si0n0xsinqssc7g46zld7ip20q9il0jqnxvjaqvx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      super."docstring-parser"
      super."google-api-core"
      super."google-auth"
      super."google-cloud-bigquery"
      super."google-cloud-resource-manager"
      super."google-cloud-storage"
      super."packaging"
      super."proto-plus"
      super."protobuf"
      super."pydantic"
      super."shapely"
      super."typing-extensions"
    ];
  };
}
